version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker
      - gateway
      - ui

  messageBroker:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    container_name: messageBroker
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - socialMediaManagerNetwork

  gateway:
    build: ./services/gateway
    volumes:
      - ./services/gateway:/services/gateway
      - rabbitmq-utils:/services/gateway/utils
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker  
  
  socket:
    build: ./services/socket
    volumes:
      - ./services/socket:/services/socket
      - rabbitmq-utils:/services/socket/utils
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker

  formatter:
    build: ./services/formatter
    volumes:
      - ./services/formatter:/services/formatter
      - rabbitmq-utils:/services/formatter/utils
    restart: unless-stopped
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker

  twitter:
    build: ./services/twitter
    volumes:
      - ./services/twitter:/services/twitter
      - rabbitmq-utils:/services/twitter/utils
    restart: unless-stopped
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker
      
  linkedin:
    build: ./services/linkedin
    volumes:
      - ./services/linkedin:/services/linkedin
      - rabbitmq-utils:/services/linkedin/utils
    restart: unless-stopped
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - messageBroker

  ui:
    build: ./ui
    volumes:
      - ./ui:/app/ui
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - gateway

volumes:
  rabbitmq-utils:
    name: "rabbitmq-utils-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/services/utils'

networks:
  socialMediaManagerNetwork:
    driver: bridge